/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/pe.v:1.1-45.10" *)
module pe(clk, rst_n, weight_in, act_in, valid_in, acc_clear, acc_out, skipped, mac_valid);
  (* src = "rtl/pe.v:26.1-42.4" *)
  wire [31:0] _00_;
  (* src = "rtl/pe.v:37.22-37.52" *)
  wire [31:0] _01_;
  wire _02_;
  (* src = "rtl/pe.v:25.27-25.35" *)
  wire _03_;
  (* src = "rtl/pe.v:23.29-23.56" *)
  wire _04_;
  (* src = "rtl/pe.v:37.33-37.51" *)
  wire [31:0] _05_;
  wire [31:0] _06_;
  (* src = "rtl/pe.v:11.16-11.25" *)
  input acc_clear;
  wire acc_clear;
  (* src = "rtl/pe.v:13.39-13.46" *)
  output [31:0] acc_out;
  reg [31:0] acc_out;
  (* src = "rtl/pe.v:9.40-9.46" *)
  input [7:0] act_in;
  wire [7:0] act_in;
  (* src = "rtl/pe.v:5.16-5.19" *)
  input clk;
  wire clk;
  (* src = "rtl/pe.v:24.6-24.12" *)
  wire do_mac;
  (* src = "rtl/pe.v:22.6-22.13" *)
  wire do_skip;
  (* src = "rtl/pe.v:19.6-19.17" *)
  wire is_act_zero;
  (* src = "rtl/pe.v:18.6-18.20" *)
  wire is_weight_zero;
  (* src = "rtl/pe.v:15.16-15.25" *)
  output mac_valid;
  reg mac_valid;
  (* src = "rtl/pe.v:6.16-6.21" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/pe.v:14.16-14.23" *)
  output skipped;
  reg skipped;
  (* src = "rtl/pe.v:10.16-10.24" *)
  input valid_in;
  wire valid_in;
  (* src = "rtl/pe.v:8.40-8.49" *)
  input [7:0] weight_in;
  wire [7:0] weight_in;
  assign _01_ = $signed(acc_out) + (* src = "rtl/pe.v:37.22-37.52" *) $signed(_05_);
  (* src = "rtl/pe.v:26.1-42.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) acc_out <= 32'd0;
    else if (_02_) acc_out <= _00_;
  assign _02_ = | { do_mac, acc_clear };
  assign is_weight_zero = ! (* src = "rtl/pe.v:20.24-20.36" *) $signed(weight_in);
  assign is_act_zero = ! (* src = "rtl/pe.v:21.21-21.30" *) $signed(act_in);
  assign do_skip = valid_in && (* src = "rtl/pe.v:23.16-23.57" *) _04_;
  assign do_mac = valid_in && (* src = "rtl/pe.v:25.15-25.35" *) _03_;
  assign _03_ = ! (* src = "rtl/pe.v:25.27-25.35" *) do_skip;
  assign _04_ = is_weight_zero || (* src = "rtl/pe.v:23.29-23.56" *) is_act_zero;
  assign _05_ = $signed(weight_in) * (* src = "rtl/pe.v:37.33-37.51" *) $signed(act_in);
  (* src = "rtl/pe.v:26.1-42.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) skipped <= 1'h0;
    else skipped <= do_skip;
  (* src = "rtl/pe.v:26.1-42.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_valid <= 1'h0;
    else mac_valid <= do_mac;
  assign _06_ = do_mac ? (* src = "rtl/pe.v:36.19-36.25|rtl/pe.v:36.15-38.12" *) _01_ : 32'hxxxxxxxx;
  assign _00_ = acc_clear ? (* full_case = 32'd1 *) (* src = "rtl/pe.v:33.13-33.22|rtl/pe.v:33.9-38.12" *) 32'd0 : _06_;
endmodule
